### ISSUE TITLE
What is the code license? I presume MIT license?

### ISSUE THREAD

**Issue by WithinAmnesia** [edwardr/godot-csharp-crpg-camera#1]
Is this commercial friendly? Does this use the MIT license or something commercial friendly? Creative Commons 0 could work too.

**Comment by edwardr** [comment]
Yeah, I will make it MIT. I need to remove the Bioware background images first though.

**Comment by edwardr** [comment]
Latest update removes Bioware background and adds MIT license @WithinAmnesia

**Comment by WithinAmnesia** [comment]
Thank you very much that is very nice progress.
