### ISSUE TITLE
Can this be upgrade to use CRPG RTS elements?

### ISSUE THREAD

**Issue by WithinAmnesia** [edwardr/godot-csharp-crpg-camera#2]
There are few CRPG options for Godot 4+ and one big missing feature is open source commercial friendly / MIT / CC0 license CRPG / RTS code for Godot 4+.

I am biased, https://github.com/WithinAmnesia/ARPG I am trying to make a ARPG open source MIT License game engine template for Godot 4+ (~Diablo 2, Old BG+IWD, 2D Zelda). I wish to port old BG+IWD features to Godot and if reasonable enough to port them over as mods but keep the game engine features found with the likes of GemRB https://github.com/gemrb/gemrb but for Godot 4+

What is this? https://github.com/bbenefield89/Godot_cRpg

**Comment by edwardr** [comment]
It could be. Short list of features or modules needed for that:

- Basic game/scene manager
- Input manager to handle unit selection and commands
- Pathfinding (NavigationServer2D doesn't seem to be working in Godot 4.0+ C#)
- Basic combat system

**Comment by WithinAmnesia** [comment]
There's two project on github for godot 4 that might meet those requirements in the near future.
https://github.com/don-tnowe/godot-wyvernbox-inventory/issues/21#issuecomment-1759017822
https://github.com/spicylobstergames/shotcaller-godot
These might be merged in the future too.  Any thing that could help too. Any big plans?
